# Generated by Django 3.0.3 on 2020-09-10 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=4)),
                ('constellation', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=15)),
                ('birthplace', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('families', models.CharField(max_length=100)),
                ('intro', models.TextField(max_length=2000)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=40)),
                ('release_date', models.CharField(max_length=80)),
                ('other_names', models.CharField(max_length=40)),
                ('intro', models.TextField(max_length=3000)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('text', models.TextField(max_length=3000)),
                ('from_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Coactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('times', models.IntegerField(default=1)),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Celebrity')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='celebrity',
            name='movies',
            field=models.ManyToManyField(to='engine.Movie'),
        ),
    ]
