# Generated by Django 3.0.3 on 2020-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.FloatField(),
        ),
    ]
